### PR TITLE
Feature/tjyang pddecon

### PR DESCRIPTION
**Pull request by yangtj207**
Add a producer module to remove electronics response from photon detector waveforms through deconvolution.

### CODE REVIEW

**Comment by yangtj207** [comment]
pd
This PR adds a producer module that can improve signal to noise ratio by applying a Wiener filter and remove electronics response to get an impulse signal.

**Comment by jroto** [comment]
Hi @yangtj207, we are already applying a deconvolution to our waveforms. We remove noise by applying both a Gaussian and a Wiener filter (see [Deconvolution_module](duneopdet/OpticalDetector/Deconvolution/Deconvolution_module.cc). Were you aware of this? We want to avoid having several modules doing the same thing in the repository. Does this module have some specific feature that is not included in the present one? Please, provide some details. Thanks.

**Comment by tomjunk** [comment]
Just a few comments:

It is not unreasonable to have two modules that do the same thing in our code stack.  There is value to running alternate algorithms and comparing them.  That said, it looks like the contents of Deconvolution/Deconvolution_module.cc and PDSPCalPhoton_module.cc appear to be nearly the same -- a Weiner filter and a Gaussian filter are in both.

There are a few small issues with Deconvolution_module.cc -- one is the over-broad name "Deconvolution" which is really the only string art uses to look up the shared object.  This has a specific use -- photon detector deconvolution, and it may even be limited to a specific kind of photon detectors.  mrb will complain if someone else wants to use the module type Deconvolution however.  Another issue is the use of random numbers to fill out short waveforms in data.  In general, throwing random numbers when analyzing data is ill-advised.  You might get different answers on different runs through the data.  Are the random seeds under art's control?  And lastly, the line noise RMS is input as a fcl parameter to Deconvolution_module.cc.  This is used to generate the random number padding -- and if it differs from the RMS in data, you might have a discontinuity in the noise level of a waveform that consists of some data and some random numbers.

That said, the current PR has a Weiner filter function input as an array in FCL, which isn't really much better, as the signal and noise can vary from one channel to the next.

**Comment by jroto** [comment]
Hi @tomjunk,
Thanks for your answer. Indeed it seems reasonable to have both if the goal is to compare the performance between them. I would love to see the results of this comparison!
I ping @maridelg and @mantheys, for your suggestions about Deconvolution_module.cc. Thanks again!

**Comment by tomjunk** [comment]
Compiles fine.  Merging, and it can be run and characterized once in the release.

**Pull request merged**
