### PR TITLE
solve the problem with timing outside of active volume part.

### PR DESCRIPTION
**Pull request by Li-Jiaoyang97**
Move the `IncludePropTime` part to be inside of `PDFastSim_dune.fcl` so that it could use the correct algorithm `PropagationTimeModel` instead of the propagation timing part in `PropagationTimeModel`. 

The timing in `PropagationTimeModel` is using argon model now, as in larsim does not support `GeoPropTimeOnly` in `PDFastSimPVS_module.cc`, will follow up on this.

### CODE REVIEW

**Review by lpaulucc — COMMENTED** [review]
Things look ok to me. I think it is just worth having one clarification. 
Since we cannot use two libraries, the mixing of Ar and Xe was done in one single merged library. Ok. 
The propagation time is the Ar propagation time (this PR) because extra work is needed for Xe. Ok, we should have photons travelling short distances to reach the lateral detectors and longer distances to cathode and opposite lateral (which should be a negligible amount of light anyway). 
How about the scintillation time? I see line 82 of PDFasSim_dune.fcl is commented out now. Will the Ar scintillation time (fast+slow components) be used or will it be the Xe scintillation time (fast+slow or just slow)?

**Comment by Li-Jiaoyang97** [comment]
Hi, scintillation time is using Ar scintillation time, and fast only.

**Comment by pgreen135** [comment]
> I see. Is this also true for the semi-analytical model?

This is not the case for the semi-analytical model -- the two components (ar/xe) are treated separately there and so can be given their own timing as needed. I think the issue with the merged library is there is only one photon visibility service (and can only be one due to the way services are handled), so there isn't a way to configure the different emission times (Jiaoyang can clarify though)

**Comment by lpaulucc** [comment]
Thanks for the explanation.

**Review by lpaulucc — APPROVED** [review]

**Comment by Li-Jiaoyang97** [comment]
Hi @lpaulucc, I also enable the slow component of argon scintillation time model in the non-active volume region to follow the bug you mentioned yesterday at the meeting. See [here](https://github.com/DUNE/duneopdet/pull/19/commits/cee5d8909ea80402c3ce881f4fae244c114db9e2).

**Pull request merged**
