### PR TITLE
VD External Ar/Xe PVS config

### PR DESCRIPTION
**Pull request by lpaulucc**
Adjusting the external optical fast simulation for FD2-VD. Creating two different configs, one for Ar and another one for Xe, and adjusting the parameters accordingly.

### CODE REVIEW

**Review by pgreen135 — APPROVED** [review]
Looks good, no comments from my side.

**Comment by lpaulucc** [comment]
Thanks, @pgreen135 . I am actually getting an error while running the Xe stage, maybe you know the reason?
```
%MSG-s ArtException:  PDFastSimPVS:PDFastSimXeExternal@Construction  19-Dec-2023 07:55:39 CST ModuleConstruction
cet::exception caught in art
---- Can't find key BEGIN
  step_size 
---- Can't find key END
%MSG
```

**Comment by pgreen135** [comment]
Hm, this `step_size` parameter governs the discretisation of the timing parameterisation and should only be read when GeoPropTimeOnly is false, in https://github.com/LArSoft/larsim/blob/770bbe277fbb80b1c837d3af68484932999e4306/larsim/PhotonPropagation/PropagationTimeModel.cxx#L22 

```
if (!fGeoPropTimeOnly) {
      // Direct / VUV
      mf::LogInfo("PropagationTimeModel") << "Using VUV timing parameterization";
      fstep_size = VUVTimingParams.get<double>("step_size");
```

So suggests there's a configuration error -- perhaps do a fhicl-dump to double-check this parameter is being set as you expect?

**Comment by pgreen135** [comment]
@Li-Jiaoyang97 the GeoPropTimeOnly parameter would need to be read in PDFastSimPVS and passed in the construction of the propagation time class. Looking now, I'm not sure this has been implemented correctly? I only see it in PDFastSimPAR But you are more of the expert on that code, so should comment.

**Comment by Li-Jiaoyang97** [comment]
Hi @pgreen135, I have just followed up this with @lpaulucc on slack. Yes, I confirm the `GeoPropTimeOnly` is not being read properly in `PDFastSimPVS` model on `larsim`.  We should submit a PR for larsim.

**Comment by tomjunk** [comment]
This PR is approved, but has one pending reviewer and some conversation which seems to indicate that it is not yet finished, waiting for a PR to be made in larsim. As that could take some time, should we convert this PR to a draft?

**Comment by lpaulucc** [comment]
Hi Tom, sorry for the late reply. This PR can be merged. I discussed with Jiaoyang on slack and adjusted the configurations to what can be used at the moment without getting errors. A change in larsim will be needed to address the issue but we should go ahead as it is.

**Pull request merged**
