### PR TITLE
Add light yield map tools

### PR DESCRIPTION
**Pull request by TylerLaBree**

### CODE REVIEW

**Comment by lpaulucc** [comment]
Hi Tyler, thanks for the PR. Do you believe you could include a header in all files? In there, you would put a small description of the purpose of the file and also information on the authorship. Some more comments on specific functions, mainly in LightYieldMap.h, would be very helpful. We may improve things in the future (like providing maps along the width or the length of the detector or extracting dimensions from larsoft itself and some other things which are currently hard coded in the files).

**Comment by TylerLaBree** [comment]
Hi @lpaulucc I've added comments to functions, objects, and files, changed some function names to better reflect their purpose, and put my name and school at the top of each file. I agree that it'd be great to pull the voxel dimensions from the data file, so the process can be more automated in the future. Let me know if there's anything else I can do for now to ready this PR for merge.

**Comment by calcuttj** [comment]
trigger build

**Review by lpaulucc — APPROVED** [review]
Thank you, Tyler, for the changes.

**Pull request merged**
