### PR TITLE
Hybrid model for fast light sim 

### PR DESCRIPTION
**Pull request by Li-Jiaoyang97**
`PDFastSim_dune.fcl` is modified to allow the merged library to be used for the non-active volume part. In the `photpropservices_dune.fcl`, the `dune10kt_vd_1x8x14_photonvisibilityservice_ArXe` service is also declared for the library.

### CODE REVIEW

**Review by lpaulucc — CHANGES_REQUESTED** [review]
Jiaoyang, could you please included in the fhicl file a description of the details (reflectivity, absorption length...) of the parameters used for the semi-analytical model? Otherwise we may forget the assumptions later. This also goes for the hybrid library (fast/slow ratio, Ar/Xe ratio...)

**Comment by Li-Jiaoyang97** [comment]
The summary of the absorption length, reflectivity for the semi-analytical model and the the contribution of the merged library are listed in the slides [here](https://indico.fnal.gov/event/55146/contributions/245602/attachments/157027/206180/DUNE-vd-light.pdf).

**Comment by lpaulucc** [comment]
Thank you, Jiaoyang. I think there is one issue with the library, though. I also invite @msorel to comment on that. Protodune data (both SP and DP) saw a cut in Ar light and the fact that not all late late goes into Xe. We are implementing that for the semi-analytical model using the parameters updated in this [PR](https://github.com/DUNE/duneopdet/pull/7/files#diff-375353e708b60c558aaaf417f916f043620ce61c18ab82645419ace2e738f545). Unfortunately, since there is just one library, we cannot do the same at the detsim stage for the external volume. If we want to keep things consistent, this has to go into the merged library.

**Review by lpaulucc — APPROVED** [review]
Changes in the code as just what we need. New mixed library on the way.

**Pull request merged**
