### PR TITLE
Updating library build tools and flash match

### PR DESCRIPTION
**Pull request by lpaulucc**
This PR has a large amount of modified files.
- in LibraryBuildTools: this folder was really outdated. Fhicl files for generating libraries were returning empty trees, for instance. All fhicls were moved to a new folder (legacy) for historical reasons. The submit file was also updated and a new fhicl was included for generating a test library (protodunehd).
- in the FlashMatch algorithm: some modifications were made in order to get the energy deposition by the particle of interest in the presence of backgrounds. New fhicl parameters were included to handle different primary particles and also NDK events when they are generated with the @local::standard_ndk module (since they are labelled as unknown type). Also, another fhicl parameter was included to allow the analyzer to record flashes from events with vertex located between the field cage and cryostat wall in FD2-VD (currently used in SNB analysis). The FlashMatch fhicl file was updated and VD specific names and parameters were included. The fhicl files in dunesw will be updated to use the new definitions (and removing additional parameters put by hand in them) once this PR is merged not to cause any disruption. HD fhicls will not have to be modified.

### CODE REVIEW

**Comment by calcuttj** [comment]
trigger build

**Comment by calcuttj** [comment]
trigger build

**Comment by calcuttj** [comment]
@lpaulucc Hi Laura, is this ready to be merged in?

**Comment by lpaulucc** [comment]
Hi Jake, yes, it can be merged. Thanks!

**Pull request merged**
