### PR TITLE
FIRST UPLOAD SOLAR FLASH PRODUCER

### PR DESCRIPTION
**Pull request by mantheys**
Trying to make the solar analysis more modular. Start with a producer for solar flash (work in progress).

### CODE REVIEW

**Comment by lpaulucc** [comment]
Hi Sergio, thank you for that. What would be the main difference from the standard flash finder?

**Comment by mantheys** [comment]
Hi! The standard flash is an algorithm designed for high-energy events. In general, I found it produced flashes that covered too much of the TPC (even both sides in the case of HD) and produced too many candidates without many options for tuning. I'm developing an ophit clustering algorithm (the code lives in duneana/SolarNuAna/AdjOpHitsUtils - PR pending) for the context of solar neutrinos that produces flashes based on time and channel proximity by triggering on a single ophit channel. The goal is to make it simpler, sharper, faster, and with better centroid determination for matching. This PR is just the producer that calls the external function and dumps the product. It is also a good template for other Lowe Flash algorithms that anyone could try because it's very minimal and straightforward.

**Comment by lpaulucc** [comment]
Thank you for the explanation, Sergio. It seems it wouldn't just be a matter of adjusting the flash parameters.

**Comment by lpaulucc** [comment]
Since it depends on a PR which is pending, should it be made a draft PR instead until the other one is ready to go?

**Comment by aolivier23** [comment]
Tom recommended I try to force this to merge to fix a CI failure from another PR.

**Pull request merged**
